source data:
  wap_allo:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vAct_Water_TakeWaterWAPAllocation
    col_names: [RecordNumber, Activity, SW Allocation Block, WAP, Allocation Rate (l/s), From Month, To Month, First Stream Depletion Rate, Second Stream Depletion Rate, 'Include in SW Allocation?']
    rename_cols: [RecordNumber, take_type, sw_allo_block, WAP, AllocatedRate, FromMonth, ToMonth, SD1, SD2, Include in SW Allocation]

  wap_sd:
    server: SQL2012PROD04
    database: Wells
    table: Well_StreamDepletion_Locations
    col_names: [Well_No, NZTMXwell, NZTMYwell, NZTMX, NZTMY, SD1_7, SD1_30, SD1_150, NZTMX2, NZTMY2, SD2_7, SD2_30, SD2_150, ModifiedDate]
    rename_cols: [WAP, NZTMX, NZTMY, SD1_NZTMX, SD1_NZTMY, SD1_7Day, SD1_30Day, SD1_150Day, SD2_NZTMX, SD2_NZTMY, SD2_7Day, SD2_30Day, SD2_150Day, ModifiedDate]

  consented_takes:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vAct_Water_TakeWaterPermitAuthorisation
    col_names: [RecordNumber, Activity, Consented Annual Volume (m3/year), 'Has a lowflow restriction condition?', Consent Max Rate (l/s), Consent Max Vol (m3), Consent Max Consec Days]
    rename_cols: [RecordNumber, take_type, ConsentedAnnualVolume, lowflow condition, ConsentedRate, ConsentedMultiDayVolume, ConsentedMultiDayPeriod]

  allocated_volume:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vAct_Water_TakeWaterPermitVolume
    col_names: [RecordNumber, Activity, Allocation Block, Effective Annual Volume (m3/year), 'Include in allocation?']
    rename_cols: [RecordNumber, take_type, gw_allo_block, AllocatedAnnualVolume, Include in allocation]

  water_use:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vAct_Water_TakeWaterPermitUse
    col_names: [RecordNumber, Activity, Water Use, Irrigation Of, Primary Irrigation type, Irrigation Area (ha), Max Rate (l/s), Volume (m3), Consecutive Day Period]
    rename_cols: [RecordNumber, UseType, WaterUse, IrrigationOf, PrimaryIrrigationType, IrrigationArea, Rate, MultiDayVolume, MultiDayPeriod]

  # monitor_sites:
  #   server: SQL2012PROD04
  #   database: Accela
  #   table: Ecan.vAct_Water_MonitoringSites
  #   col_names: [RecordNumber, Site ID, Site Type]
  #   rename_cols: [RecordNumber, SiteID, SiteType]

  divert:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vAct_Water_Divertwater_Water
    col_names: [RecordNumber, Activity, WAP, Max Rate (l/s), Volume (m3), Consecutive Day Period, 'Has a lowflow restriction condition?']
    rename_cols: [RecordNumber, DivertType, WAP, Rate, MultiDayVolume, MultiDayPeriod, lowflow condition]

  joint_permits:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vAct_Water_AssociatedPermits
    col_names: [RecordNumber, Record Number, Relationship, Combined Annual Vol. (m3), Status]
    rename_cols: [RecordNumber, OtherRecordNumber, Relationship, CombinedAnnualVolume, Status]

  parent_child:
    server: SQL2012PROD04
    database: Accela
    table: Ecan.vQA_Relationship_Actuals
    col_names: [parent RecordNo, child RecordNo]
    rename_cols: [ParentRecordNumber, ChildRecordNumber]

  permit:
    server: SQL2012PROD03
    database: datawarehouse
    table: F_ACC_Permit
    col_names: [B1_ALT_ID, B1_APPL_STATUS, HolderEcanID, fmDate, toDate, ModifiedDate, Longitude, Latitude]
    rename_cols: [RecordNumber, ConsentStatus, EcanID, FromDate, ToDate, ModifiedDate, lon, lat]

output:
  server: edwDEV01
  database: ConsentsReporting
