source data:
  wap_allo:
    server: SQL02Prod
    database: Accela
    table: Ecan.vAct_Water_TakeWaterWAPAllocation
    col_names: [RecordNumber, Activity, SW Allocation Block, WAP, Allocation Rate (l/s), From Month, To Month, First Stream Depletion Rate, Second Stream Depletion Rate, 'Include in SW Allocation?']
    rename_cols: [RecordNumber, take_type, sw_allo_block, WAP, AllocatedRate, FromMonth, ToMonth, SD1, SD2, IncludeInSwAllocation]
    pk: ['RecordNumber', 'take_type', 'sw_allo_block', 'WAP', 'FromMonth']

  wap_sd:
    server: SQL03Prod
    database: Wells
    table: Well_StreamDepletion_Locations
    col_names: [Well_No, NZTMX, NZTMY, SD1_7, SD1_30, SD1_150, NZTMX2, NZTMY2, SD2_7, SD2_30, SD2_150]
    rename_cols: [ExtSiteID, SD1_NZTMX, SD1_NZTMY, SD1_7Day, SD1_30Day, SD1_150Day, SD2_NZTMX, SD2_NZTMY, SD2_7Day, SD2_30Day, SD2_150Day]
    pk: [ExtSiteID]

  consented_takes:
    server: SQL02Prod
    database: Accela
    table: Ecan.vAct_Water_TakeWaterPermitAuthorisation
    col_names: [RecordNumber, Activity, Consented Annual Volume (m3/year), 'Has a lowflow restriction condition?', Consent Max Rate (l/s), Consent Max Vol (m3), Consent Max Consec Days]
    rename_cols: [RecordNumber, take_type, ConsentedAnnualVolume, LowflowCondition, ConsentedRate, ConsentedMultiDayVolume, ConsentedMultiDayPeriod]
    pk: [RecordNumber, take_type]

  allocated_volume:
    server: SQL02Prod
    database: Accela
    table: Ecan.vAct_Water_TakeWaterPermitVolume
    col_names: [RecordNumber, Activity, Allocation Block, Effective Annual Volume (m3/year), Full Annual Volume (m3/year), 'Include in allocation?']
    rename_cols: [RecordNumber, take_type, allo_block, AllocatedAnnualVolume, FullAnnualVolume, IncludeInAllocation]
    pk: [RecordNumber, take_type, allo_block]

  water_use:
    server: SQL02Prod
    database: Accela
    table: Ecan.vAct_Water_TakeWaterPermitUse
    col_names: [RecordNumber, Activity, Water Use, Irrigation Of, Primary Irrigation type, Irrigation Area (ha), Max Rate (l/s), Volume (m3), Consecutive Day Period]
    rename_cols: [RecordNumber, UseType, WaterUse, IrrigationOf, PrimaryIrrigationType, IrrigationArea, ConsentedRate, ConsentedMultiDayVolume, ConsentedMultiDayPeriod]
    pk: [RecordNumber, UseType, WaterUse]

  # monitor_sites:
  #   server: SQL02Prod
  #   database: Accela
  #   table: Ecan.vAct_Water_MonitoringSites
  #   col_names: [RecordNumber, Site ID, Site Type]
  #   rename_cols: [RecordNumber, SiteID, SiteType]

  divert:
    server: SQL02Prod
    database: Accela
    table: Ecan.vAct_Water_Divertwater_Water
    col_names: [RecordNumber, Activity, WAP, Max Rate (l/s), Volume (m3), Consecutive Day Period, 'Has a lowflow restriction condition?']
    rename_cols: [RecordNumber, DivertType, WAP, ConsentedRate, ConsentedMultiDayVolume, ConsentedMultiDayPeriod, LowflowCondition]
    pk: [RecordNumber, DivertType, WAP]

  linked_permits:
    server: SQL02Prod
    database: Accela
    table: Ecan.vAct_Water_AssociatedPermits
    col_names: [RecordNumber, Record Number, Relationship, Combined Annual Vol. (m3), Status]
    rename_cols: [RecordNumber, OtherRecordNumber, Relationship, CombinedAnnualVolume, LinkedStatus]
    pk: [RecordNumber, OtherRecordNumber]

  parent_child:
    server: SQL02Prod
    database: Accela
    table: Ecan.vQA_Relationship_Actuals
    col_names: [parent RecordNo, child RecordNo, parent Category, child Category]
    rename_cols: [ParentRecordNumber, ChildRecordNumber, ParentCategory, ChildCategory]
    pk: [ParentRecordNumber, ChildRecordNumber]

  permit:
    server: SQL03Prod
    database: GIS_Accela
    table: vCOCOA_NZTM_ResourceConsents
    col_names: [ConsentNo, ConsentStatus, ECNumber, fmDate, toDate, NZTMX, NZTMY]
    rename_cols: [RecordNumber, ConsentStatus, EcanID, FromDate, ToDate, NZTMX, NZTMY]
    pk: [RecordNumber]

  sites:
    server: SQL02Prod
    database: usm
    table: Site
    col_names: [UpstreamSiteID, Name, NZTMX, NZTMY]
    rename_cols: [ExtSiteID, SiteName, NZTMX, NZTMY]
    pk: [ExtSiteID]

misc:
  HydroFeature:
    HydroFeature: [Surface Water, Groundwater]
  Activities:
    ActivityType: [Take, Divert, Discharge, Dam, Use]
  Attributes:
    Attribute: [IrrigationOf, PrimaryIrrigationType, IrrigationArea]
  use_types_codes:
    'agriculture': ['Irrigation', 'Intensive Farming', 'Arable Farming', 'Aquaculture', 'Intensive (Shed) Farming - Dairy', 'Intensive (shed) Farming - Other', 'Intensive (shed) Farming - Poultry', 'Intensive (Shed) Farming - Beef', 'Scheme - Irrigation']
    'stockwater': ['Stockwater', 'Dairy Shed (Washdown/Cooling)', 'Intensive (shed) Farming - Pork', 'Scheme - Stockwater']
    'industry': ['Industrial Use', 'Cooling Water', 'Construction', 'Drainage', 'Dewatering - Temporary', 'De-watering - Long-Term', 'Gravel Extraction/Processing', 'Heat exchange - HVAC', 'Heat exchange - non HVAC', 'Manufacturing - Food Products', 'Manufacturing - Other', 'Manufacturing - Water Bottling', 'Mining', 'Industrial Use - Food Products', 'Industrial Use - Water Bottling', 'Industrial Use - Other', 'Manufacturing - Beverage', 'Manufacturing - Meat Processing', 'Manufacturing - Timber processing', 'Manufacturing - Vege processing']
    'water_supply': ['Public Water Supply', 'Domestic Use', 'Potable Supply']
    'hydroelectric': ['Power Generation', 'Hydroelectirc Power Generation']
    'other': ['Augment Flow/Wetland/Aquifer', 'Firefighting', 'Fisheries/Wildlife Management', 'Flood Control', 'Frost Protection', 'Landfill', 'REVIEW', 'Research (incl testing)', 'Snow Making', 'Stormwater', 'Waste Water', 'Water Storage - To', 'Swimming Pool', 'Amenity - non-consumptive', 'Artifical Lake/pond', 'Water Storage - From', 'Realignment of stream']
  use_types_priorities: ['hydroelectric', 'water_supply', 'agriculture', 'stockwater', 'industry', 'other']

output:
  server: edwDEV01
  database: ConsentsReporting
